{
    "type": "bundle",
    "id": "bundle--3dae2db4-c41c-4e5a-8972-6468da971fd3",
    "spec_version": "2.0",
    "objects": [
        {
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "id": "relationship--0d3f773c-ed0e-4db4-8457-204a7a33eb58",
            "type": "relationship",
            "created": "2020-05-18T17:31:39.484Z",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "external_references": [
                {
                    "source_name": "McAfee Maze March 2020",
                    "url": "https://www.mcafee.com/blogs/other-blogs/mcafee-labs/ransomware-maze/",
                    "description": "Mundo, A. (2020, March 26). Ransomware Maze. Retrieved May 18, 2020."
                }
            ],
            "modified": "2020-06-24T01:40:07.453Z",
            "description": "[Maze](https://attack.mitre.org/software/S0449) has checked the language of the infected system using the \"GetUSerDefaultUILanguage\" function.(Citation: McAfee Maze March 2020)",
            "relationship_type": "uses",
            "source_ref": "malware--d9f7383c-95ec-4080-bbce-121c9384457b",
            "target_ref": "attack-pattern--354a7f88-63fb-41b5-a801-ce3b377b36f1",
            "x_mitre_version": "1.0",
            "x_mitre_modified_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5"
        }
    ]
}